server:
  port: 8082
  tomcat:
    max-threads: 20
spring:
  application:
    name: location-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: ${spring.application.name}
