server:
  port: 8084
spring:
  application:
    name: service-d
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: ${spring.application.name}
