server:
  port: 8086
spring:
  application:
    name: cart-service
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/
    service:
      name: ${spring.application.name}
